name: Publish a release
#
on:
  push:
    branches: 
      [main]

env:
  NODE_VERSION: 12

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -  name: build
       run: | 
        npm run lint
        npm run build
        npm pack


  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: npm ci
      - run: echo "registry=https://npm.pkg.github.com/@hirenrparghi" >> .npmrc
      - run: npm run build
      - run: npm publish --access public $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
